USE [PowerBI]
GO

/****** Object:  View [DPO].[vCLAIM_TYPE_RATIO]    Script Date: 30/09/2022 16:38:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [DPO].[vCLAIM_TYPE_RATIO] AS SELECT DISTINCT TYPE FROM CLAIM_RATIO
GO


