USE [PowerBI]
GO

/****** Object:  View [DPO].[vTERRITORY]    Script Date: 30/09/2022 16:44:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [DPO].[vTERRITORY] AS SELECT DISTINCT TERRITORY, [TERRITORY_CODE]--, OFFICE_CODE, OFFICE
FROM Main_AD_STRUCTURE
WHERE Territory is not null
GO


