USE [PowerBI]
GO

/****** Object:  View [DPO].[Cal_AD_Pending]    Script Date: 30/09/2022 16:31:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE   VIEW [DPO].[Cal_AD_Pending]
AS
WITH PD AS 
(SELECT SALEOFFICE, 
		AGNTNUM, 
		APPLICATION_NUMBER, 
		CONTRACT_NUMBER, 
		CONTRACT_STATUS, 
		FIRST_PREMIUM, 
		SUBMIT_AMT, 
		EFFECTIVE_DATE, 
		TRANSACTION_DATE, 
		FIRST_ISSUED_DATE, 
		ISSUED_DATE
FROM   DPO.DP_POSubmitDA
WHERE CONTRACT_STATUS != 'IF'
)

SELECT	PD_1.SALEOFFICE, 
		PD_1.AGNTNUM, 
		PD_1.APPLICATION_NUMBER, 
		PD_1.CONTRACT_NUMBER, 
		PD_1.CONTRACT_STATUS, 
		PD_1.FIRST_PREMIUM, 
		PD_1.SUBMIT_AMT, 
		PD_1.EFFECTIVE_DATE, 
		PD_1.TRANSACTION_DATE, 
		PD_1.FIRST_ISSUED_DATE, 
		PD_1.ISSUED_DATE,
		N.[DESCRIPTON PENDING DOC], 
        A.AD_Code, 
		A.AD_Code + REPLACE(CAST(PD_1.TRANSACTION_DATE AS date), '-', '') AS ID
FROM PD AS PD_1 
LEFT OUTER JOIN DPO.DW_Agent AS A 
ON PD_1.AGNTNUM = A.Code
LEFT JOIN NBU_CHDAGPDC N
ON PD_1.APPLICATION_NUMBER = N.APPLICATION_NUMBER
GO


