USE [PowerBI]
GO

/****** Object:  View [DPO].[vClaimPending]    Script Date: 30/09/2022 16:38:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [DPO].[vClaimPending] AS SELECT [CLAIM_NO]
      ,[POLICY_NUMBER]
      ,[LA_NAME]
      ,[COMPONENT_CODE]
      ,[CLAIM_NATURE]
      ,[SUM_ASSURED]
      ,[STATUS]
      ,[REQUEST_NUMBER]
      ,[AGENT_NAME]
      ,[AGENT_CODE]
      ,[AD_NAME]
      ,[AD_OFFICES]
      ,[SCAN_LOCATION]
      ,[PROPOSAL_DATE]
      ,[RISK_COMMENCEMENT_DATE]
      ,[PAID_TO_DATE]
      ,[CLM_SUBMIT_DATE]
      ,[EVENT_DATE]
      ,[ADMISSION_DATE]
      ,[DISCHARGE_DATE]
      ,[LOS_DAYS]
      ,[TREATMENT]
      ,[HOSPITAL]
      ,[DIAGNOSTIC_RESULT]
      ,[ICD_CODE]
      ,[INVESTIGATION_STR]
      ,[LETTER_DATE_1]
      ,[LETTER_DATE_2]
      ,[FULLY_DATE]
      ,[CLOSED_DATE]
      ,[TOTAL]
      ,[CLAIM_DECISION]
      ,[TERM_CONDITION]
      ,CASE WHEN [REASON_REJECT] = '' THEN NULL
						ELSE REASON_REJECT
				END REASON_REJECT
				
      ,[PAYMENT_NOTICED]
      ,[REFUND_AMOUNT]
      ,[CLAIM_STATUS]
      ,[PAID_DATE1]
      ,[LA_NUMBER]
      ,[APPROVAL_DAYS]
      ,[DAY_ICU]
      ,[CLAIM_DECISION_MASTER]
      ,[DECISION_DATE]
      , AD_CODE
			, TERRITORY
		, TAT_FUNCTION

, CASE WHEN A.TAT_FUNCTION <= 4 THEN '0-4 days'
			WHEN A.TAT_FUNCTION > 4 AND A.TAT_FUNCTION <=10 THEN '5-10 days'
			WHEN A.TAT_FUNCTION > 10 AND A.TAT_FUNCTION <=20 THEN '11-20 days'
			WHEN A.TAT_FUNCTION > 20 AND A.TAT_FUNCTION <=30 THEN '21-30 days'
			ELSE '30++ days'
		END TAT_FUNCTION_GROUPS

	, GROUP_CLAIM_DECISION
	, NON_DISCLOSED
/*	, CASE WHEN (MONTH(FULLY_DATE) > MONTH(CLM_SUBMIT_DATE) AND INVESTIGATION_STR = 'N' AND MONTH(DECISION_DATE) = MONTH(PAYMENT_NOTICED) AND YEAR(DECISION_DATE) = YEAR(PAYMENT_NOTICED)) 
						OR (FULLY_DATE IS NULL AND LETTER_DATE_1 IS NOT NULL) THEN 'Supplement'
			WHEN (MONTH(FULLY_DATE) > MONTH(CLM_SUBMIT_DATE) AND INVESTIGATION_STR = 'Y' AND MONTH(DECISION_DATE) = MONTH(PAYMENT_NOTICED) AND YEAR(DECISION_DATE) = YEAR(PAYMENT_NOTICED)) THEN 'Supplement + Investigation'
			WHEN (MONTH(DECISION_DATE) < MONTH(PAYMENT_NOTICED) AND YEAR(DECISION_DATE) = YEAR(PAYMENT_NOTICED)) THEN 'Worksheet'
			WHEN (MONTH(FULLY_DATE) > MONTH(CLM_SUBMIT_DATE) AND INVESTIGATION_STR = 'N' AND DECISION_DATE IS NULL AND PAYMENT_NOTICED IS NULL) OR (YEAR(FULLY_DATE) > YEAR(CLM_SUBMIT_DATE))THEN 'Supplement'
		ELSE NULL
	END REASON_PENDING*/
	, CASE WHEN CLAIM_DECISION_MASTER IS NULL AND INVESTIGATION_STR = 'Y' AND FULLY_DATE IS NULL AND (LETTER_DATE_1 IS NOT NULL OR LETTER_DATE_2 IS NOT NULL) THEN 'Supp & Invest'
				WHEN CLAIM_DECISION_MASTER IS NULL AND INVESTIGATION_STR = 'N' AND FULLY_DATE IS NULL AND (LETTER_DATE_1 IS NOT NULL OR LETTER_DATE_2 IS NOT NULL) THEN 'Supplement'
				WHEN CLAIM_DECISION_MASTER IS NULL AND INVESTIGATION_STR = 'Y' AND FULLY_DATE IS NULL AND (LETTER_DATE_1 IS NULL AND LETTER_DATE_2 IS NULL) THEN 'Investigation'
				WHEN CLAIM_DECISION_MASTER IS NULL AND INVESTIGATION_STR = 'Y' AND FULLY_DATE IS NOT NULL AND (LETTER_DATE_1 IS NOT NULL OR LETTER_DATE_2 IS NOT NULL) THEN 'Investigation'
				WHEN CLAIM_DECISION_MASTER IS NOT NULL THEN 'Worksheet'
				ELSE NULL
		END REASON_PENDING
	, OUTSTANDING_CLAIM_NO
	
	, CASE WHEN (OUTSTANDING_CLAIM_NO IS NOT NULL AND DATEDIFF(DAY, CLM_SUBMIT_DATE, GETDATE()) <= 20) THEN '1-20 days'
			WHEN (OUTSTANDING_CLAIM_NO IS NOT NULL AND DATEDIFF(DAY, CLM_SUBMIT_DATE, GETDATE()) > 20 AND DATEDIFF(DAY, CLM_SUBMIT_DATE, GETDATE()) <= 30) THEN '20-30 days'
			--WHEN A.TAT_FUNCTION > 15 AND A.TAT_FUNCTION <= 30 THEN '16-30 days'
			WHEN (OUTSTANDING_CLAIM_NO IS NOT NULL AND DATEDIFF(DAY, CLM_SUBMIT_DATE, GETDATE()) > 30) THEN '>30 days'
			ELSE NULL
	END TAT_OUTSTANDING_GROUPS
FROM 
(
	SELECT C.* 
	, P.AD_CODE
	, [TERRITORY] = CASE WHEN (SELECT TOP 1 Territory FROM Main_AD_STRUCTURE WHERE /*status IN ('Appointed','Promoted') AND*/  AD_Code = P.AD_CODE AND Office_Code = C.AD_OFFICES ORDER BY ID DESC) IS NULL 
													THEN (SELECT TOP 1 Territory FROM Main_AD_STRUCTURE WHERE Grade IN ('ZD','SZD','TD') AND AD_Code = P.AD_CODE ORDER BY ID DESC)
												ELSE (SELECT TOP 1 Territory FROM Main_AD_STRUCTURE WHERE /*status IN ('Appointed','Promoted') AND*/  AD_Code = P.AD_CODE AND Office_Code = C.AD_OFFICES ORDER BY ID DESC) END
	
		, CASE WHEN PAYMENT_NOTICED IS NULL THEN DATEDIFF(DAY, CLM_SUBMIT_DATE, GETDATE())
					ELSE NULL--chô null này tính lại 
			END TAT_FUNCTION
		, CASE WHEN (INVESTIGATION_STR = 'Y' AND FULLY_DATE IS NOT NULL AND (DATEDIFF(DAY, FULLY_DATE, DECISION_DATE) > 30 OR PAYMENT_NOTICED IS NULL)  ) THEN CLAIM_NO
				ELSE NULL
			END [OUTSTANDING_CLAIM_NO]
	FROM 
	/*(
		SELECT * FROM [dbo].[CLAIM]
		WHERE MONTH(CLM_SUBMIT_DATE) < MONTH(PAYMENT_NOTICED) AND YEAR(CLM_SUBMIT_DATE) = YEAR(PAYMENT_NOTICED)
		AND YEAR(CLM_SUBMIT_DATE) >= 2020 AND PAYMENT_NOTICED IS NOT NULL
		UNION
		SELECT * FROM CLAIM	WHERE YEAR(CLM_SUBMIT_DATE) >= 2020
		AND PAYMENT_NOTICED IS NULL AND CLAIM_STATUS IN ('Pending')
		
	)C*/
	CLAIM C	
	LEFT JOIN Main_POLICY_INFO P ON P.POLICY_NUMBER = C.POLICY_NUMBER
	WHERE --YEAR(C.CLM_SUBMIT_DATE) = '2020'
	CLAIM_STATUS IN ('Pending')
)A --WHERE INVESTIGATION_STR = 'Y'
GO


