USE [PowerBI]
GO

/****** Object:  View [DPO].[vPS_REPORTS]    Script Date: 30/09/2022 16:43:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [DPO].[vPS_REPORTS] AS SELECT [ID]
      ,[POLICY_NO]
      ,[PO_NAME]
      ,[AGENT_AREA]
      ,[AD_CODE]
      ,[SALES_UNIT]
      ,[TRANSACTION_TYPE]
      ,[REQUEST_DATE]
      ,[RECEIVED_DATE]
      ,[LAST_RECEIVED_DATE]
      ,[LCA]
      ,[STATUS]
      ,[PROCESSED_DATE]
      ,[PROCESSED_BY]
      ,[REMARKS]
      ,[NEW_SA_BASIC]
      ,[NEW_PREMIUM]
      ,[TRANSACTION_DETAILS]
      ,[POLICY_YEAR] = CASE WHEN [POLICY_YEAR] = '> Year 4' THEN 'Year 4++' ELSE POLICY_YEAR END 
      ,[TRANSACTION_FROM]
      ,[OLD_SA]
      ,[OLD_Premium]
      ,[RCD]
      ,[PROD_GROUP]
      ,[CHANGE_BILL]
			--,CHANGE_TYPE_GROUP
			,STATUS_GROUP
			,TAT_Days
			
			, TERRITORY
			, CASE WHEN A.TAT_Days <= 1 THEN '1 day'
					--WHEN A.TAT_Days = 1 THEN '1 day'
					WHEN A.TAT_Days > 1 AND A.TAT_Days <= 5 THEN '2-5 day'
					WHEN A.TAT_Days > 5 AND A.TAT_Days <= 10 THEN '6-10 day'
					ELSE '>10 days'
				END TAT_GROUPS
				
			,[LEVEL]
			,ALTERATIONS
FROM (
SELECT R.*
	, T.[LEVEL]
	, T2.ALTERATIONS
	, CASE WHEN R.LAST_RECEIVED_DATE <> '' THEN DATEDIFF(DAY, R.LAST_RECEIVED_DATE, R.PROCESSED_DATE)
		ELSE DATEDIFF(DAY, R.RECEIVED_DATE, R.PROCESSED_DATE) END TAT_Days
		
	, [TERRITORY] = CASE WHEN (SELECT TOP 1 Territory FROM Main_AD_STRUCTURE WHERE AD_Code = R.AD_CODE AND Office_Code = R.AGENT_AREA ORDER BY ID DESC) IS NULL 
													THEN (SELECT TOP 1 Territory FROM Main_AD_STRUCTURE WHERE Grade IN ('ZD','SZD','TD') AND AD_Code = R.AD_CODE ORDER BY ID DESC)
												ELSE (SELECT TOP 1 Territory FROM Main_AD_STRUCTURE WHERE AD_Code = R.AD_CODE AND Office_Code = R.AGENT_AREA ORDER BY ID DESC) END
	
		
FROM PS_REPORTS R LEFT JOIN PS_TRANSACTION_TYPE T ON T.TRANSACTION_TYPE = R.TRANSACTION_TYPE
LEFT JOIN PS_TRANSACTION_TYPE T2 ON T2.TRANSACTION_TYPE = R.TRANSACTION_TYPE
--LEFT JOIN Main_POLICY_INFO P ON P.POLICY_NUMBER = R.POLICY_NO WHERE R.POLICY_NO = '80066432'
)A
GO


