USE [PowerBI]
GO

/****** Object:  View [DPO].[vNBU_NEWBUSINESS]    Script Date: 30/09/2022 16:42:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [DPO].[vNBU_NEWBUSINESS] AS SELECT 
	A.* 
	
	, [TERRITORY] = CASE WHEN (SELECT TOP 1 Territory FROM DPO.Main_AD_STRUCTURE WHERE /*status IN ('Appointed','Promoted') AND*/  AD_Code = A.AD_CODE AND Office_Code = A.AREA_NAME ORDER BY ID DESC) IS NULL 
													THEN (SELECT TOP 1 Territory FROM DPO.Main_AD_STRUCTURE WHERE Grade IN ('ZD','SZD','TD') AND AD_Code = A.AD_CODE ORDER BY ID DESC)
												ELSE (SELECT TOP 1 Territory FROM DPO.Main_AD_STRUCTURE WHERE /*status IN ('Appointed','Promoted') AND*/  AD_Code = A.AD_CODE AND Office_Code = A.AREA_NAME ORDER BY ID DESC) END
		
	, CASE WHEN A.[FUNCTION_DAYS] >= 0 AND A.[FUNCTION_DAYS] <= 2 THEN '0-2 days'
			WHEN A.[FUNCTION_DAYS] > 2 AND A.[FUNCTION_DAYS] <= 3 THEN '3 days'
			WHEN A.[FUNCTION_DAYS] > 3 AND A.[FUNCTION_DAYS] <= 4 THEN '4 days'
			WHEN A.[FUNCTION_DAYS] > 4 THEN '5++ days'
			ELSE NULL
		END TAT_FUNCTION_GROUPS
		
	, CASE WHEN A.CUSTOMER_DAYS >= 0 AND A.CUSTOMER_DAYS <= 5 THEN '0-5 days'
			WHEN A.CUSTOMER_DAYS > 5 AND A.CUSTOMER_DAYS <= 10 THEN '6-10 days'
			WHEN A.CUSTOMER_DAYS > 10 AND A.CUSTOMER_DAYS <= 15 THEN '11-15 days'
			WHEN A.CUSTOMER_DAYS > 15 THEN '16++ days'
			ELSE NULL
	END TAT_CUSTOMER_GROUPS
	
FROM (
	SELECT [POLICY NUMBER] POLICY_NUMBER
      ,[POLICY STATUS] POLICY_STATUS
      ,[PROPOSAL RECEIVED DATE] PROPOSAL_RECEIVED_DATE
      ,[DECISION DATE] DECISION_DATE
			,[SEQNO]
			,[CREATE CODE DATE] CREATE_CODE_DATE, [CLOSE CODE DATE] CLOSE_CODE_DATE
		
			, [SEQ_DAYS] = CASE WHEN (SELECT * FROM fn_CountWorkingDays([CREATE CODE DATE], [CLOSE CODE DATE])) < 1 THEN 0
														ELSE (SELECT * FROM fn_CountWorkingDays([CREATE CODE DATE], [CLOSE CODE DATE])) - 1
														END
			
      ,[ACK_DATE]
			,[CLEAN_CASE] = CASE WHEN SEQNO IS NULL THEN 'Clean' ELSE 'Non-Clean' END
      ,p.SALES_UNIT, p.AREA_NAME, p.AD_CODE
			
			,[FUNCTION_DAYS] = CASE WHEN SEQNO IS NULL THEN 
																 CASE WHEN (SELECT * FROM fn_CountWorkingDays([PROPOSAL RECEIVED DATE], [DECISION DATE])) < 1 THEN 0 
																			ELSE (SELECT * FROM fn_CountWorkingDays([PROPOSAL RECEIVED DATE], [DECISION DATE])) - 1
																			END
															ELSE CASE WHEN (SELECT * FROM fn_CountWorkingDays([CLOSE CODE DATE], [DECISION DATE])) < 1 THEN 0
																				ELSE (SELECT * FROM fn_CountWorkingDays([CLOSE CODE DATE], [DECISION DATE])) - 1
																			END
													END
			, DATEDIFF(DAY, nb.[PROPOSAL RECEIVED DATE], nb.[ACK_DATE]) 'CUSTOMER_DAYS'
			
			,[ADD_DOC_DAYS] = CASE WHEN (SELECT * FROM fn_CountWorkingDays([PROPOSAL RECEIVED DATE], [CREATE CODE DATE])) < 1 THEN 0 
																			ELSE (SELECT * FROM fn_CountWorkingDays([PROPOSAL RECEIVED DATE], [CREATE CODE DATE])) - 1
																			END
																													 
															
			
	FROM DPO.NBU_NEWBUSINESS nb LEFT JOIN DPO.Main_POLICY_INFO p ON p.POLICY_NUMBER = nb.[POLICY NUMBER]
)A
GO


