USE [PowerBI]
GO

/****** Object:  View [DPO].[vwREEVPF]    Script Date: 30/09/2022 16:47:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [DPO].[vwREEVPF] AS
SELECT [CHDRCOY]
      ,[CHDRNUM]
      ,[EFFDATE]
      ,[LIFE]
      ,[COVERAGE]
      ,[RIDER]
      ,[CRTABLE]
      ,[SUMINS]
      ,[RISK_CESS_TERM]
      ,[PREM_CESS_TERM]
      ,[CRRCD]
      ,[ZLINSTPREM]
      ,[INSTPREM]
      ,[AEXTPRM]
      ,[APREM]
      ,[CURRFROM]
      ,[VALIDFLAG]
      ,[STATCODE]
      ,[PSTATCODE]
      ,[TRANCDE]
      ,[TRANDSC]
      ,[OCCPCLAS]
      ,[ZOCCDSC]
      ,[SMOKING]
      ,[REINDTE]
      ,[INSTPRDC]
      ,[YRSINF]
      ,[OPCDA01]
      ,[OPCDA02]
      ,[OPCDA03]
      ,[OPCDA04]
      ,[OPCDA05]
      ,[OPPC01]
      ,[OPPC02]
      ,[OPPC03]
      ,[OPPC04]
      ,[OPPC05]
      ,[AGERATE01]
      ,[AGERATE02]
      ,[AGERATE03]
      ,[AGERATE04]
      ,[AGERATE05]
      ,[INSPRM01]
      ,[INSPRM02]
      ,[INSPRM03]
      ,[INSPRM04]
      ,[INSPRM05]
      ,[EXT_CESS_TERM01]
      ,[EXT_CESS_TERM02]
      ,[EXT_CESS_TERM03]
      ,[EXT_CESS_TERM04]
      ,[EXT_CESS_TERM05]
      ,[UNIT_VIRTUAL_FUND01]
      ,[UNIT_VIRTUAL_FUND02]
      ,[UNIT_VIRTUAL_FUND03]
      ,[UNIT_VIRTUAL_FUND04]
      ,[UNIT_VIRTUAL_FUND05]
      ,[FUND_AMOUNT01]
      ,[FUND_AMOUNT02]
      ,[FUND_AMOUNT03]
      ,[FUND_AMOUNT04]
      ,[FUND_AMOUNT05]
      ,[RGPYMOP01]
      ,[RGPYMOP02]
      ,[RGPYMOP03]
      ,[RGPYMOP04]
      ,[RGPYMOP05]
      ,[PYMT01]
      ,[PYMT02]
      ,[PYMT03]
      ,[PYMT04]
      ,[PYMT05]
      ,[ANNAME01]
      ,[ANNAME02]
      ,[ANNAME03]
      ,[ANNAME04]
      ,[ANNAME05]
      ,[ANNAGE01]
      ,[ANNAGE02]
      ,[ANNAGE03]
      ,[ANNAGE04]
      ,[ANNAGE05]
      ,[SANNAME01]
      ,[SANNAME02]
      ,[SANNAME03]
      ,[SANNAME04]
      ,[SANNAME05]
      ,[SANNAGE01]
      ,[SANNAGE02]
      ,[SANNAGE03]
      ,[SANNAGE04]
      ,[SANNAGE05]
      ,[FIRST_PAYDATE01]
      ,[FIRST_PAYDATE02]
      ,[FIRST_PAYDATE03]
      ,[FIRST_PAYDATE04]
      ,[FIRST_PAYDATE05]
      ,[NEXT_PAYDATE01]
      ,[NEXT_PAYDATE02]
      ,[NEXT_PAYDATE03]
      ,[NEXT_PAYDATE04]
      ,[NEXT_PAYDATE05]
      ,[FINAL_PAYDATE01]
      ,[FINAL_PAYDATE02]
      ,[FINAL_PAYDATE03]
      ,[FINAL_PAYDATE04]
      ,[FINAL_PAYDATE05]
      ,[TOTAMNT01]
      ,[TOTAMNT02]
      ,[TOTAMNT03]
      ,[TOTAMNT04]
      ,[TOTAMNT05]
      ,[USER_PROFILE]
      ,[JOB_NAME]
      ,[DATIME]
  FROM [PowerBI].[DPO].[REEVPF]
GO


