USE [PowerBI]
GO

/****** Object:  View [DPO].[vwCLAIM_AE]    Script Date: 30/09/2022 16:45:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [DPO].[vwCLAIM_AE] AS

WITH REEVPF1 AS(


--SELECT R.[CHDRNUM] + R.[LIFE] + R.[COVERAGE] + R.[CRTABLE] AS [KEY 1]
--		,[OCCPCLAS] 
--FROM
--(SELECT 
--    [CHDRNUM], [LIFE], [COVERAGE],[CRTABLE]
--    ,MAX([EFFDATE]) AS [EFFDATE]
    	 
--FROM [PowerBI].[DPO].[vwREEVPF]
--GROUP BY [CHDRNUM], [LIFE], [COVERAGE],[CRTABLE]) AS R1
--INNER JOIN [PowerBI].[DPO].[vwREEVPF] R
--ON (R1.[CHDRNUM] = R.[CHDRNUM] AND R1.[LIFE] = R.[LIFE] AND R1.[COVERAGE] = R.[COVERAGE] AND R1.[CRTABLE] = R.[CRTABLE] AND R1.[EFFDATE] = R.[EFFDATE])



SELECT 
    [CHDRNUM]
    ,[EFFDATE]
    ,[LIFE]
    ,[COVERAGE]
    ,[CRTABLE]
    ,[OCCPCLAS]
	,RANK() OVER(PARTITION BY [CHDRNUM], [LIFE], [COVERAGE],[CRTABLE]  ORDER  BY [EFFDATE] DESC) AS [Rank]
	 
FROM [PowerBI].[DPO].[vwREEVPF]
--where CHDRNUM = '80000047'
), REEVPF2 AS(

SELECT [CHDRNUM] + [LIFE] + [COVERAGE] + [CRTABLE] AS [KEY 1], OCCPCLAS
FROM REEVPF1
WHERE [Rank]=1
), CLM_EXP AS 

(SELECT
	a.[KEY 1],
	a.CHDRNUM,
	a.ISSUED_AGE,
	a.SEX,
	a.SUMINS as SA,
	CASE
		WHEN a.[CRTABLE] IN ('UL01','UL02','UL03','UL04','ES01','EN01','EE01','ETR1'
			,'EC01','EC02','TBA','EN03','EN04','TL01','EE02','EE03','EN05','EN06'
			,'EN07','EE04','RTR1','URT3','URT2','RTR2','UL05', 'UL06','URT5') THEN 'Death/TPD'
		WHEN a.[CRTABLE] IN ('URA3','RAC1','RAC2','URA1', 'RAD1','RAD2','URA5') THEN'AC'
		WHEN a.[CRTABLE] IN ('URC3','URC1','RCI1','URC5') THEN 'CI'
		WHEN a.[CRTABLE] IN ('URC4','RCI2','URC2','URC6') THEN 'CI Lady'
		WHEN a.[CRTABLE] IN ('URH1','URH3','RHB1') THEN 'HI'
		ELSE 'Other'
	END AS [Claim Type],
	a.CURRFROM,
	a.[LAST OVER DUE DATE],
	a.CRRCD,
	a.STATCODE,
	r.OCCPCLAS,
	a.[CRTABLE]
FROM vwACT_R_RAW a
LEFT JOIN REEVPF2 r ON a.[KEY 1]=r.[KEY 1])

(SELECT E.*,
	R.Premium_Rate*E.SA*0.0008 as Yearly_Premium
FROM CLM_EXP E
LEFT JOIN [DPO].[vwCLAIM_PREMIUM_RATE] AS R ON E.[Claim Type] = R.Claim_Type AND E.ISSUED_AGE = R.ALB AND E.SEX = R.Sex
WHERE E.[Claim Type] IN ('HI', 'CI'))
UNION
(SELECT E.*, 
	R.Premium_Rate*E.SA*.0008 as Yearly_Premium
FROM CLM_EXP E
LEFT JOIN [DPO].[vwCLAIM_PREMIUM_RATE] AS R ON E.[Claim Type] = R.Claim_Type AND E.OCCPCLAS = R.Class
WHERE E.[Claim Type] = 'AC')
UNION
(SELECT E.*,
	(R.Premium_Rate*E.SA*.5 + R.Female_Early*E.SA*.25 + R.Female_Recover*E.SA*.25)*.0008 as Yearly_Premium
FROM CLM_EXP E
LEFT JOIN [DPO].[vwCLAIM_PREMIUM_RATE] AS R ON E.[Claim Type] = R.Claim_Type AND E.ISSUED_AGE = R.ALB AND E.SEX = R.Sex
WHERE E.[Claim Type] = 'CI Lady')
UNION
(SELECT E.*,
	R.Premium_Rate*E.SA*0.0008 as Yearly_Premium
FROM CLM_EXP E
LEFT JOIN [DPO].[vwCLAIM_PREMIUM_RATE] AS R ON E.[Claim Type] = R.Claim_Type AND E.ISSUED_AGE = R.ALB AND E.SEX = R.Sex
WHERE E.[Claim Type] = 'Death/TPD' AND E.CRTABLE NOT IN ('EC01', 'EC02'))

UNION
(SELECT E.*,
	(R.Premium_Rate + CI.Premium_Rate)*E.SA*0.0008 as Yearly_Premium
FROM CLM_EXP E
LEFT JOIN [DPO].[vwCLAIM_PREMIUM_RATE] AS R ON E.[Claim Type] = R.Claim_Type AND E.ISSUED_AGE = R.ALB AND E.SEX = R.Sex
LEFT JOIN [DPO].[vwCLAIM_PREMIUM_RATE] AS CI ON CI.Claim_Type = 'CI' AND E.ISSUED_AGE = CI.ALB AND E.SEX = CI.Sex
WHERE E.[Claim Type] = 'Death/TPD' AND E.CRTABLE IN ('EC01', 'EC02'))

GO


