USE [PowerBI]
GO

/****** Object:  View [DPO].[vPS_PREMIUM]    Script Date: 30/09/2022 16:43:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Script for SelectTopNRows command from SSMS  ******/
CREATE   VIEW [DPO].[vPS_PREMIUM] AS
SELECT  [ROWID]
      ,[TRANNO]
      ,[RDOCNUM]
      ,[RLDGACCT]
      ,[SACSCODE]
      ,[SACSTYP]
      ,[PRODUCT_CODE]
      ,[AGENT_CLASS]
      ,[AGENT_AREA]
      ,[SERVICING_AGENT]
      ,[BATCTRCDE]
      ,[TRANDESC]
      ,[BF_ORG_DCAMT]
      ,[ORG_PREM_APPLIED]
      ,[PREMIUM_APPLIED]
      ,[ORG_DISCOUNT_AMT]
      ,[DISCOUNT_AMT]
      ,[AFYP_BF_DCAMT]
      ,[FYP_BF_DCAMT]
      ,[FYP_DCAMT]
      ,[AFYP]
      ,[FYP]
      ,[RYP]
      ,[TOPUP_PREMIUM]
      ,CAsT(CAST([CALCULATED_DATE] AS VARCHAR) AS date) AS [CALCULATED_DATE]
      ,CAsT(CAST([RISK_COMMENCE_DATE] AS VARCHAR) AS date) AS [RISK_COMMENCE_DATE]
      ,CAsT(CAST([COLLECTED_DATE] AS VARCHAR) AS date) AS [COLLECTED_DATE]
      ,CAsT(CAST([TRANSACTION_DATE] AS VARCHAR) AS date) AS [TRANSACTION_DATE]
      ,[CONTRACT_STATUS]
      ,[POLICY_YEAR]
      ,[POLICY_TERM]
      ,[PREMIUM_YEAR]
      ,[PREMIUM_TERM]
      ,[FREQUENCY]
      ,CAsT(CAST([FIRST_ISSUE_DATE] AS VARCHAR) AS date) AS [FIRST_ISSUE_DATE]
      ,CAsT(CAST([ISSUED_DATE] AS VARCHAR) AS date) AS [ISSUED_DATE]
      ,CAsT(CAST([EFFECTIVE_DATE] AS VARCHAR) AS date) AS [EFFECTIVE_DATE]
      ,CAsT(CAST([CURRENT_DUE_DATE] AS VARCHAR) AS date) AS [CURRENT_DUE_DATE]
      ,CAsT(CAST([PAID_TO_DATE] AS VARCHAR) AS date) AS [PAID_TO_DATE]
      ,CAsT(CAST([NEXT_DUE_DATE] AS VARCHAR) AS date) AS [NEXT_DUE_DATE]
      ,CAsT(CAST([POLICY_ACKNOWLEDGE_DATE] AS VARCHAR) AS date) AS [POLICY_ACKNOWLEDGE_DATE]
      ,CAsT(CAST([TRANSFER_DATE] AS VARCHAR) AS date) AS [TRANSFER_DATE]
      ,[TARGET_PREMIUM]
      ,[SUM_ASSURED]
      ,[FREE_LOOK_DATE]
      ,CAsT(CAST([PRO_RECIEVED_DATE] AS VARCHAR) AS date) AS [PRO_RECIEVED_DATE]
      ,CAsT(CAST([STATUS_DATE] AS VARCHAR) AS date) AS [STATUS_DATE]
      ,CAsT(CAST([LAPSED_DATE] AS VARCHAR) AS date) AS [LAPSED_DATE]
      ,CAsT(CAST([TERMINATED_DATE] AS VARCHAR) AS date) AS [TERMINATED_DATE]
      ,[AGE_CUSTOMER]
      ,[ISSUING_AGENT]
  FROM [PowerBI].[DPO].[PS_PREMIUM]
  --WHERE [RDOCNUM] = '80013317'
  --ORDER BY [COLLECTED_DATE]
GO


