USE [DP_Manh]
GO

/****** Object:  StoredProcedure [dbo].[AD_BIGCONTRACT_BUDGET_BONUS]    Script Date: 21/02/2023 09:37:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[AD_BIGCONTRACT_BUDGET_BONUS] (@varREPORT_MONTH nvarchar(4000)) 
AS 
BEGIN
----@varREPORT_MONTH format as 'yyyy-mm-01'
WITH AD_STRUCTURE AS (
	SELECT 
		AD_STRUCTURE2.[TERRITORY],
		AD_STRUCTURE1.*
	FROM (SELECT *
		  FROM [SQL_SV65].[PowerBI].[DPO].[Main_AD_STRUCTURE_FULL]
		  WHERE [ExplodedDate]  = @varREPORT_MONTH) AS AD_STRUCTURE1
	LEFT JOIN [dbo].[T_Main_TERRITORIES] AS AD_STRUCTURE2
	ON AD_STRUCTURE1.[Territory_Code] = AD_STRUCTURE2.[CODE]
)
, BIG_CONTRACT_DETAIL AS (
	SELECT
		*
	FROM [DP_Manh].[dbo].[T_BIG_CONTRACT_BUDGET_DETAIL]
	WHERE [REPORT_MONTH] = FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM')
)
----SUM BONUS
, A AS (
	SELECT
		[AD_Code],
		[ADName],
		[AD_Grade],
		COUNT([Policy_Number]) AS SOLUONG_HD,
		SUM([IP_COUNT_BONUS_FINAL]) AS IP_DAT_THUONG,
		SUM([BONUS]) AS TONG_THUONG
	FROM BIG_CONTRACT_DETAIL
	WHERE [IP_COUNT_BONUS_FINAL] >= 40000000
	GROUP BY [AD_Code], [ADName], [AD_Grade]
)
----JOIN TO AD STRUCTURE
--, B AS (
	SELECT
		B02.TERRITORY,
		--B02.[STD],
		--B02.[STDName],
		B02.[TD],
		B02.[TDName],
		B02.[TAD],
		B02.[TADName],
		B02.[SRD],
		B02.[SRDName],
		B02.[RD],
		B02.[RDName],
		B02.[RAD],
		B02.[RADName],
		B01.*,
		FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM') AS REPORT_MONTH
	FROM A AS B01 LEFT JOIN AD_STRUCTURE AS B02
	ON B01.AD_Code = B02.[AD_Code]
--)



END;
GO


