USE [DP_Manh]
GO

/****** Object:  StoredProcedure [dbo].[AD_TOP_RECRUIT_QUARTERLY]    Script Date: 15/02/2023 13:20:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[AD_TOP_RECRUIT_QUARTERLY] (@varREPORT_MONTH nvarchar(4000)) 
AS 
BEGIN
--@varREPORT_MONTH format 'yyyy-MM-01'
----PREPARING DATA
WITH
PREMIUM_CO AS (
	SELECT *
	FROM [DP_Manh].[dbo].[T_DP_TAGENTPREMIUM_TEST_CUTOFF]
	WHERE [CUTOFF] = FORMAT(EOMONTH(@varREPORT_MONTH), 'yyyyMMdd')
)
, AGT_INFO_CO AS (
	SELECT *
	FROM [DP_Manh].[dbo].[T_Main_AGENT_INFO_DA_CUTOFF]
	WHERE [CUTOFF] = FORMAT(EOMONTH(@varREPORT_MONTH), 'yyyyMMdd')
)
, DAILYSALES_FULL AS (
	SELECT 
		[Agent Code]
      ,[Policy_Number]
      ,[Issuing_Agent]
      ,[Contract Type]
      ,[Component_Code]
      ,[Proposal_Receive_Date]
      ,[Policy_Issue_Date]
      ,[Sum_Assured]
      ,[Before_Discount_Premium]
      ,[Discount_Premium]
      ,[After_Discount_Premium]
      ,[Policy_Status]
      ,[Bill_Frequency]
      ,[Modal_Factor]
      ,[Lapsed_date]
      ,[AFYP]
      ,[RISK_COMMENCE_DATE]
      ,[CUTOFF]
	FROM [DP_Manh].[dbo].[T_DP_TDAILYSALES_DA_CUTOFF]
	WHERE [CUTOFF] = FORMAT(EOMONTH(@varREPORT_MONTH), 'yyyyMMdd')
	UNION ALL
	SELECT
		[Agent Code]
      ,[Policy_Number]
      ,[Issuing_Agent]
      ,[Contract Type]
      ,[Component_Code]
      ,[Proposal_Receive_Date]
      ,[Policy_Issue_Date]
      ,[Sum_Assured]
      ,[Before_Discount_Premium]
      ,[Discount_Premium]
      ,[After_Discount_Premium]
      ,[Policy_Status]
      ,[Bill_Frequency]
      ,[Modal_Factor]
      ,[Lapsed_date]
      ,[AFYP]
      ,[RISK_COMMENCE_DATE]
      ,[CUTOFF]
	FROM [DP_Manh].[dbo].[T_DP_DA_Daily_DC_PO_WD_NT_CUTOFF]
	WHERE [CUTOFF] = FORMAT(EOMONTH(@varREPORT_MONTH), 'yyyyMMdd')
)
, AD_STRUCTURE AS (
	SELECT 
		AD_STRUCTURE2.[TERRITORY],
		AD_STRUCTURE1.*
	FROM (SELECT *
		  FROM [SQL_SV65].[PowerBI].[DPO].[Main_AD_STRUCTURE_FULL]
		  WHERE [ExplodedDate]  = @varREPORT_MONTH) AS AD_STRUCTURE1
	LEFT JOIN [dbo].[T_Main_TERRITORIES] AS AD_STRUCTURE2
	ON AD_STRUCTURE1.[Territory_Code] = AD_STRUCTURE2.[CODE]
)
-----------TINH ACTIVE AGENT
, A0 AS (
	SELECT 
		A01.*,
		A02.Policy_Issue_Date AS Policy_Issue_Date_FULL
	FROM PREMIUM_CO AS A01 LEFT JOIN DAILYSALES_FULL AS A02
	ON A01.[Policy No] = A02.Policy_Number
)
, A AS (
	SELECT DISTINCT
		[Issuing Agent],
		[Policy No],
		[Policy Status],
		Policy_Issue_Date_FULL,
		CASE 
		WHEN [Policy Status] = 'IF' THEN 1
		WHEN [Policy Status] IN ('FL', 'PO', 'DC', 'WD', 'NT', 'CF')
			AND ((Policy_Issue_Date_FULL NOT BETWEEN @varREPORT_MONTH AND EOMONTH(@varREPORT_MONTH)) OR Policy_Issue_Date_FULL IS NULL)
		THEN -1
		ELSE 0 END AS CountPolicy
	FROM A0
	WHERE Policy_Issue_Date_FULL BETWEEN @varREPORT_MONTH AND EOMONTH(@varREPORT_MONTH)
	OR ([Policy Status] != 'IF' AND [Collected Date] BETWEEN @varREPORT_MONTH AND EOMONTH(@varREPORT_MONTH))
)
, A1 AS (
	SELECT
		[Issuing Agent],
		SUM(CountPolicy) AS CC,
		CASE
			WHEN SUM(CountPolicy) > 0 then 1
			WHEN SUM(CountPolicy) = 0 then 0
			WHEN SUM(CountPolicy) < 0 then 0
		END AS AA
	FROM A
	GROUP BY [Issuing Agent]
)
, A2 AS (
	SELECT
		A21.Sales_Unit_Code,
		A22.[Issuing Agent],
		A22.CC,
		A22.AA
	FROM AGT_INFO_CO AS A21 LEFT JOIN A1 AS A22
	ON A21.Agent_Number = A22.[Issuing Agent]
)
, A3 AS (
	SELECT
		Sales_Unit_Code,
		SUM(CC) AS TOTAL_CC,
		SUM(AA) AS TOTAL_ACTIVE_AGENT
	FROM A2
	GROUP BY Sales_Unit_Code
)
----TINH SO RECRUIT
, B AS (
	SELECT
		Sales_Unit_Code,
		Agent_Number
	FROM AGT_INFO_CO
	WHERE  Date_Appointed BETWEEN @varREPORT_MONTH AND EOMONTH(@varREPORT_MONTH)
	AND Agent_Status = 'Enforce'
	AND Agent_Name NOT LIKE 'DUMMY%'
	AND License_No NOT LIKE 'TAPSU%'
	AND Agent_Number NOT LIKE '6999%'
	AND SFC <> 'S'
	AND Area_Name NOT IN ('ACB', 'DSR', 'DR1', 'TTU')
)
, B1 AS (
	SELECT
		Sales_Unit_Code,
		COUNT(Agent_Number) AS TOTAL_RECRUIT
	FROM B
	GROUP BY Sales_Unit_Code
)
----TINH SO TERMINATED
, C AS (
	SELECT
		Sales_Unit_Code,
		Agent_Number
	FROM AGT_INFO_CO
	WHERE  Terminated_date BETWEEN @varREPORT_MONTH AND EOMONTH(@varREPORT_MONTH)
	AND Agent_Status = 'Terminated'
	AND Agent_Name NOT LIKE 'DUMMY%'
	AND License_No NOT LIKE 'TAPSU%'
	AND Agent_Number NOT LIKE '6999%'
	AND SFC <> 'S'
	AND Area_Name NOT IN ('ACB', 'DSR', 'DR1', 'TTU')
)
, C1 AS (
	SELECT
		Sales_Unit_Code,
		COUNT(Agent_Number) AS TOTAL_TERMINATED
	FROM C
	GROUP BY Sales_Unit_Code
)
----SUM UP RESULT
, D0 AS (
	SELECT
		D01.[STD],
		D01.[TD],
		D01.[TAD],
		D01.[SRD],
		D01.[RD],
		D01.[RAD],
		D01.[SZD],
		D01.[ZD],
		D01.[AD_Code],
		D03.TOTAL_RECRUIT,
		D02.TOTAL_CC,
		D02.TOTAL_ACTIVE_AGENT,
		D04.TOTAL_TERMINATED
	FROM AD_STRUCTURE AS D01 LEFT JOIN A3 AS D02
	ON D01.[AD_Code] = D02.Sales_Unit_Code
	LEFT JOIN B1 AS D03 
	ON D01.[AD_Code] = D03.Sales_Unit_Code
	LEFT JOIN C1 AS D04
	ON D01.[AD_Code] = D04.Sales_Unit_Code
)
, D1 AS (
	SELECT
		ZD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE ZD IS NOT NULL 
	GROUP BY ZD
	UNION
	SELECT
		SZD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE SZD IS NOT NULL 
	GROUP BY SZD
	UNION
	SELECT
		RAD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE RAD IS NOT NULL 
	GROUP BY RAD
	UNION
	SELECT
		RD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE RD IS NOT NULL 
	GROUP BY RD
	UNION
	SELECT
		SRD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE SRD IS NOT NULL 
	GROUP BY SRD
	UNION
	SELECT
		TAD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
	  SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE TAD IS NOT NULL 
	GROUP BY TAD
	UNION
	SELECT
		TD AS AD_CODE_FINAL,
		SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D0
	WHERE TD IS NOT NULL 
	GROUP BY TD
	--UNION
	--SELECT
	--	STD AS AD_CODE_FINAL,
	--	SUM(TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
	--  SUM(TOTAL_CC) AS SUM_TOTAL_CC,
	--	SUM(TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
	--	SUM(TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	--FROM D0
	--WHERE STD IS NOT NULL 
	--GROUP BY STD
)
, D2 AS (
	SELECT
		AD_CODE_FINAL,
		SUM(SUM_TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		SUM(SUM_TOTAL_CC) AS SUM_TOTAL_CC,
		SUM(SUM_TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		SUM(SUM_TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED
	FROM D1
	GROUP BY AD_CODE_FINAL
)
----FINAL
	SELECT
		AD_CODE_FINAL,
		IIF(SUM_TOTAL_RECRUIT IS NULL, 0, SUM_TOTAL_RECRUIT) AS SUM_TOTAL_RECRUIT,
		IIF(SUM_TOTAL_CC IS NULL, 0, SUM_TOTAL_CC) AS SUM_TOTAL_CC,
		IIF(SUM_TOTAL_ACTIVE_AGENT IS NULL, 0, SUM_TOTAL_ACTIVE_AGENT) AS SUM_TOTAL_ACTIVE_AGENT,
		IIF(SUM_TOTAL_TERMINATED IS NULL, 0, SUM_TOTAL_TERMINATED) AS SUM_TOTAL_TERMINATED,
		FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM') AS REPORT_MONTH
	FROM D2


END;
GO


