USE [DP_Manh]
GO

/****** Object:  StoredProcedure [dbo].[AD_BONUS_RYP_QTRLY]    Script Date: 12/01/2023 15:45:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[AD_BONUS_RYP_QTRLY] (@varREPORT_MONTH nvarchar(4000)) 
AS 
BEGIN
--@varREPORT_MONTH FORMAT THANG CUOI QUY VD Q3 = 'yyyy-09-01'
----PREPARING DATA----
WITH
PY2_RATE AS (
	SELECT
		*
	FROM [dbo].[T_AD_BONUS_PY2_RATE]
	WHERE [REPORT_MONTH] = FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM')
)
, DETAIL_RYP AS (
	SELECT
		*
	FROM [dbo].[T_AD_BONUS_DETAIL_RYP]
)
, AD_STRUCTURE AS (
	SELECT 
		AD_STRUCTURE2.[TERRITORY],
		AD_STRUCTURE1.*
	FROM (SELECT *
		  FROM [SQL_SV65].[PowerBI].[DPO].[Main_AD_STRUCTURE_FULL]
		  WHERE [ExplodedDate]  = @varREPORT_MONTH) AS AD_STRUCTURE1
	LEFT JOIN [dbo].[T_Main_TERRITORIES] AS AD_STRUCTURE2
	ON AD_STRUCTURE1.[Territory_Code] = AD_STRUCTURE2.[CODE]
)
----GROUP RYP BY AD----
, A AS (
	SELECT
		TD,
		TAD,
		SRD,
		RD,
		RAD,
		SZD,
		ZD,
		AD_Code,
		SUM(RYP) AS SUM_RYP,
		SUM(RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM DETAIL_RYP
	WHERE [REPORT_MONTH] BETWEEN  FORMAT(DATEADD(month, -2, @varREPORT_MONTH), 'yyyyMM') 
	AND FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM')
	GROUP BY TD, TAD, SRD, RD, RAD, SZD, ZD, AD_Code
)
, A1 AS (
	SELECT
		ZD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE ZD IS NOT NULL
	GROUP BY ZD
	UNION
	SELECT
		SZD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE SZD IS NOT NULL
	GROUP BY SZD
	UNION
	SELECT
		RAD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE RAD IS NOT NULL
	GROUP BY RAD
	UNION
	SELECT
		RD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE RD IS NOT NULL
	GROUP BY RD
	UNION
	SELECT
		SRD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE SRD IS NOT NULL
	GROUP BY SRD
	UNION
	SELECT
		TAD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE TAD IS NOT NULL
	GROUP BY TAD
	UNION
	SELECT
		TD AS AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A
	WHERE TD IS NOT NULL
	GROUP BY TD
)
, A2 AS (
	SELECT
		AD_CODE_FINAL,
		SUM(SUM_RYP) AS SUM_RYP,
		SUM(SUM_RYP_COUNT_BONUS) AS SUM_RYP_COUNT_BONUS
	FROM A1
	GROUP BY AD_CODE_FINAL
)
----JOIN KET QUA
, B AS (
	SELECT
		B01.[Territory_Code],
		B01.TERRITORY,
		B01.[TDName],
		B01.[TADName],
		B01.[SRDName],
		B01.[RDName],
		B01.[RADName],
		B01.[SZDName],
		B01.[ZDName],
		B01.[AD_Code],
		B01.[ADName],
		B01.[AD_Grade],
		B02.SUM_RYP,
		B02.SUM_RYP_COUNT_BONUS,
		B03.PY2_RATE,
		CASE
			WHEN B03.PY2_RATE >= 0.9 THEN 0.005
			WHEN B03.PY2_RATE >= 0.85 THEN 0.004
			WHEN B03.PY2_RATE >= 0.8 THEN 0.003
			WHEN B03.PY2_RATE >= 0.7 THEN 0.002
			WHEN B03.PY2_RATE IS NULL THEN 0.002
			ELSE 0
		END AS BONUS_RYP_RATIO,
		B01.[TD],
		B01.[TAD],
		B01.[SRD],
		B01.[RD],
		B01.[RAD],
		B01.[SZD],
		B01.[ZD]
	FROM AD_STRUCTURE AS B01 LEFT JOIN A2 AS B02 ON B01.[AD_Code] = B02.AD_CODE_FINAL
	LEFT JOIN PY2_RATE AS B03 ON B01.[AD_Code] = B03.AD_CODE_FINAL
	WHERE (B01.[Terminated_Date] IS NULL OR B01.[Terminated_Date] >= EOMONTH(@varREPORT_MONTH))
)
, B1 AS (
	SELECT
		[Territory_Code],
		TERRITORY,
		[TDName],
		[TADName],
		[SRDName],
		[RDName],
		[RADName],
		[SZDName],
		[ZDName],
		[AD_Code],
		[ADName],
		[AD_Grade],
		SUM_RYP,
		SUM_RYP_COUNT_BONUS,
		PY2_RATE,
		BONUS_RYP_RATIO,
		(SUM_RYP_COUNT_BONUS * BONUS_RYP_RATIO) AS RYP_BONUS,
		TD,
		TAD,
		SRD,
		[RD],
		[RAD],
		[SZD],
		[ZD]
	FROM B
)
----FINAL
SELECT
	TERRITORY,
	[TDName],
	[TADName],
	[SRDName],
	[RDName],
	[RADName],
	[SZDName],
	[ZDName],
	[AD_Code],
	[ADName],
	[AD_Grade],
	SUM_RYP,
	SUM_RYP_COUNT_BONUS,
	PY2_RATE,
	BONUS_RYP_RATIO,
	RYP_BONUS,
	TD,
	TAD,
	SRD,
	[RD],
	[RAD],
	[SZD],
	[ZD],
	FORMAT(DATEADD(month, -2, @varREPORT_MONTH), 'yyyyMM') + '-' +
	FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM') AS REPORT_MONTH
FROM B1
--WHERE [Territory_Code] IN ('MB1', 'MB2', 'MT', 'HCM2', 'HCM3', 'MK1')

END;
GO


