USE [DP_Manh]
GO

/****** Object:  StoredProcedure [dbo].[AD_BONUS_PY2_RATE]    Script Date: 02/12/2022 16:45:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[AD_BONUS_PY2_RATE] (@varREPORT_MONTH nvarchar(4000)) 
AS 
BEGIN
WITH AD_STRUCTURE AS (
	SELECT 
		AD_STRUCTURE2.[TERRITORY],
		AD_STRUCTURE1.*
	FROM (SELECT *
		  FROM [SQL_SV65].[PowerBI].[DPO].[Main_AD_STRUCTURE_FULL]
		  ) AS AD_STRUCTURE1
	LEFT JOIN [dbo].[T_Main_TERRITORIES] AS AD_STRUCTURE2
	ON AD_STRUCTURE1.[Territory_Code] = AD_STRUCTURE2.[CODE]
)
, A AS (
	SELECT
		 CAST([Report month] AS date) AS REPORT_MONTH
		,[Sales_Unit_Code] AS [AD Code]
		,[Sales Unit] AS [AD Name]
		,SUM([Collected]) AS [Actual Premium]
		,SUM([Original Pre]) [Expected Premium]
	FROM [SQL_SV64].[PowerBI].[DPO].[PS_PY2]
	GROUP BY [Report month], [Sales_Unit_Code], [Sales Unit]
)
, A0 AS (
	SELECT
		A02.TD,
		A02.SRD,
		A02.RD,
		A02.RAD,
		A02.SZD,
		A02.ZD,
		A01.[AD Code],
		A01.REPORT_MONTH,
		A01.[Actual Premium],
		A01.[Expected Premium]
	FROM A AS A01 LEFT JOIN AD_STRUCTURE AS A02
	ON A01.[AD Code] = A02.[AD_Code]
	AND A01.REPORT_MONTH = A02.[ExplodedDate]
	WHERE A01.REPORT_MONTH BETWEEN DATEADD(month, -5, @varREPORT_MONTH) AND @varREPORT_MONTH
)
, B0 AS (
	SELECT
		ZD AS AD_CODE_FINAL,
		SUM([Actual Premium]) AS SUM_ACTUAL_PREMIUM,
		SUM([Expected Premium]) AS SUM_EXPECTED_PREMIUM
	FROM A0
	WHERE ZD IS NOT NULL
	GROUP BY ZD
	UNION
	SELECT
		SZD AS AD_CODE_FINAL,
		SUM([Actual Premium]) AS SUM_ACTUAL_PREMIUM,
		SUM([Expected Premium]) AS SUM_EXPECTED_PREMIUM
	FROM A0
	WHERE SZD IS NOT NULL
	GROUP BY SZD
	UNION
	SELECT
		RAD AS AD_CODE_FINAL,
		SUM([Actual Premium]) AS SUM_ACTUAL_PREMIUM,
		SUM([Expected Premium]) AS SUM_EXPECTED_PREMIUM
	FROM A0
	WHERE RAD IS NOT NULL
	GROUP BY RAD
	UNION
	SELECT
		RD AS AD_CODE_FINAL,
		SUM([Actual Premium]) AS SUM_ACTUAL_PREMIUM,
		SUM([Expected Premium]) AS SUM_EXPECTED_PREMIUM
	FROM A0
	WHERE RD IS NOT NULL
	GROUP BY RD
	UNION
	SELECT
		SRD AS AD_CODE_FINAL,
		SUM([Actual Premium]) AS SUM_ACTUAL_PREMIUM,
		SUM([Expected Premium]) AS SUM_EXPECTED_PREMIUM
	FROM A0
	WHERE SRD IS NOT NULL
	GROUP BY SRD
	UNION
	SELECT
		TD AS AD_CODE_FINAL,
		SUM([Actual Premium]) AS SUM_ACTUAL_PREMIUM,
		SUM([Expected Premium]) AS SUM_EXPECTED_PREMIUM
	FROM A0
	WHERE TD IS NOT NULL
	GROUP BY TD
)
, B1 AS (
	SELECT
		AD_CODE_FINAL,
		SUM(SUM_ACTUAL_PREMIUM) AS SUM_ACTUAL_PREMIUM,
		SUM(SUM_EXPECTED_PREMIUM) AS SUM_EXPECTED_PREMIUM
	FROM B0
	GROUP BY AD_CODE_FINAL
)
, B2 AS (
	SELECT 
		AD_CODE_FINAL,
		SUM_ACTUAL_PREMIUM,
		SUM_EXPECTED_PREMIUM,
		ROUND(CAST(SUM_ACTUAL_PREMIUM AS FLOAT) / CAST(SUM_EXPECTED_PREMIUM AS FLOAT), 4) AS PY2_RATE,
		FORMAT(CAST(@varREPORT_MONTH AS date), 'yyyyMM') AS REPORT_MONTH
	FROM B1 
)
----FINAL
SELECT
*
FROM B2

END;
GO


